apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kubernetes-auto-ingress.fullname" . }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "kubernetes-auto-ingress.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "kubernetes-auto-ingress.fullname" . }}
    spec:
      containers:
      - name: kubernetes-auto-ingress
        image: maayanlab/kubernetes-auto-ingress:{{ .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        env:
          - name: NAMESPACE
            {{- if index .Values "watchNamespace" }}
            value: {{ index .Values "watchNamespace" | quote }}
            {{- else }}
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
            {{- end }}
          - name: ANNOTATION_KEY
            value: {{ index .Values "annotationKey" }}
          - name: INGRESS_CLASS_NAME
            value: {{ index .Values "ingressClassName" }}
          - name: INGRESS_CREATE_TLS
          {{- if index .Values "ingressCreateTLS" }}
            value: '1'
          {{ else }}
            value: ''
          {{- end }}
          - name: ADDITIONAL_INGRESS_ANNOTATIONS_HTTP
            value: {{ index .Values "extraAnnotations" "http" "ingress" | toJson | quote }}
          - name: ADDITIONAL_INGRESS_ANNOTATIONS_HTTPS
            value: {{ index .Values "extraAnnotations" "https" "ingress" | toJson | quote }}
        tty: true
      restartPolicy: Always
      serviceAccount: {{ template "kubernetes-auto-ingress.serviceAccountName" . }}