rbac:
  create: true

serviceAccount:
  create: true
  name:

annotationKey: maayanlab.cloud/ingress
ingressClassName: nginx
# ingressClassName: traefik

extraAnnotations:
  http:
    # if using nginx
    ingress:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # if using traefik
    # ingress:
    #   traefik.ingress.kubernetes.io/router.entrypoints: web
  https:
    ingress: {}
    # if using cert-manager
    # ingress:
    #   kubernetes.io/tls-acme: true
    #   cert-manager.io/cluster-issuer: cluster-issuer
    # if using traefik
    # ingress:
    #   traefik.ingress.kubernetes.io/router.entrypoints: websecure

# for deployment namespace
watchNamespace:
# for all namespaces
# watchNamespace: '*'